// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://olgdvlwdfgmxbpujdrnj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9sZ2R2bHdkZmdteGJwdWpkcm5qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NzA2ODYsImV4cCI6MjA2NTU0NjY4Nn0.wuQLsgJrsY4_kzl_k9L_2WHGklEcf6SaG1VV7tSt3cw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);